# This file is machine-generated - editing it directly is not advised

[[Calculus]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "f641eb0a4f00c343bbc32346e1217b86f3ce9dad"
uuid = "a8a17f2a-8fb6-4f2d-8143-b55912a47aaf"
version = "0.5.1"

[[CSV]]
deps = ["Dates", "Mmap", "Parsers", "PooledArrays", "SentinelArrays", "Tables", "Unicode"]
git-tree-sha1 = "290a56b2448024a1501834ee8b7d5d7004bc5ad3"
uuid = "af954ca2-4e9a-11eb-ae93-0242ac130002"
version = "0.8.2"

[[DataFrames]]
deps = ["CategoricalArrays", "Compat", "DataAPI", "Future", "InvertedIndices", "IteratorInterfaceExtensions", "LinearAlgebra", "Markdown", "Missings", "PooledArrays", "PrettyTables", "Printf", "REPL", "Reexport", "SortingAlgorithms", "Statistics", "TableTraits", "Tables", "Unicode"]
git-tree-sha1 = "b46e1deb4592a5df7416b10dfcd6b01fb194ab9a"
uuid = "3207c1b2-8d76-4813-acc5-db19fdf4bb84"
version = "0.22.2"

[[Gadfly]]
deps = ["Base64", "CategoricalArrays", "Colors", "Compose", "Contour", "CoupledFields", "DataStructures", "Dates", "Distributions", "DocStringExtensions", "Hexagons", "IndirectArrays", "IterTools", "JSON", "Juno", "KernelDensity", "LinearAlgebra", "Loess", "Measures", "Printf", "REPL", "Random", "Requires", "Showoff", "Statistics"]
git-tree-sha1 = "fce23cb26b95dd5b3b0fbc0d3e721a9a14620e5e"
uuid = "ffda7efd-fba4-4a63-98bb-7c3135193d6f"
version = "1.3.1"

[[HTTP]]
deps = ["Base64", "Dates", "IniFile", "MbedTLS", "Sockets", "URIs"]
git-tree-sha1 = "63055ee44b5c2b95ec1921edcf856c60124ff0c3"
uuid = "58432f8a-7cb6-4d30-ae5e-207bd69280ff"
version = "0.9.2"

[[HypothesisTests]]
deps = ["Combinatorics", "Distributions", "LinearAlgebra", "Random", "Rmath", "Roots", "Statistics", "StatsBase"]
git-tree-sha1 = "552892528991c3e17eb60e623f1ac94c0663eb7d"
uuid = "25d67ba8-4f74-41aa-b629-38f9f4415fb7"
version = "0.10.2"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[OnlineStats]]
deps = ["AbstractTrees", "Dates", "LinearAlgebra", "OnlineStatsBase", "OrderedCollections", "Random", "RecipesBase", "Statistics", "StatsBase", "SweepOperator"]
git-tree-sha1 = "a3d0e72ffde4f596cc148c4c6555e310dcd5b2ba"
uuid = "2ddd6897-a8a7-4778-8cc1-7b50c48b54ba"
version = "1.5.8"

[[OnlineStatsBase]]
deps = ["AbstractTrees", "Dates", "LinearAlgebra", "OrderedCollections", "Statistics", "StatsBase"]
git-tree-sha1 = "ed076aedbd3cb85731730268d60a7acfa4ac92f3"
uuid = "925886fa-5bf2-5e8e-b522-a9147a512338"
version = "1.4.4"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "c05d4bb2-6017-4001-9d38-afbdfb07f647"

[[Plots]]
deps = ["Base64", "Contour", "Dates", "FFMPEG", "FixedPointNumbers", "GR", "GeometryBasics", "JSON", "Latexify", "LinearAlgebra", "Measures", "NaNMath", "PlotThemes", "PlotUtils", "Printf", "REPL", "Random", "RecipesBase", "RecipesPipeline", "Reexport", "Requires", "Scratch", "Showoff", "SparseArrays", "Statistics", "StatsBase", "UUIDs"]
git-tree-sha1 = "539f1c69593db907a304c1dc3ac49ccb98eb283c"
uuid = "845c95bf-16e4-4e3f-9c0f-c942956615a1"
version = "1.10.0"

[[RDatasets]]
deps = ["CSV", "CodecZlib", "DataFrames", "FileIO", "Printf", "RData", "Reexport"]
git-tree-sha1 = "70951fac6528d2b932a89de4f7c5865ae8778811"
uuid = "3eeecea6-01aa-4de7-9a31-02282770c046"
version = "0.7.3"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "ff36ebc3-c250-4c0b-be4d-affe752fb018"

[[StatsBase]]
deps = ["DataAPI", "DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics"]
git-tree-sha1 = "7bab7d4eb46b225b35179632852b595a3162cb61"
uuid = "10f92b97-3fed-4a77-8508-7032e06c1677"
version = "0.33.2"

[[StatsFuns]]
deps = ["Rmath", "SpecialFunctions"]
git-tree-sha1 = "3b9f665c70712af3264b61c27a7e1d62055dafd1"
uuid = "43bd2672-d8cd-4a5f-8019-f3a2a5e22b5b"
version = "0.9.6"
