[deps]
Calculus = "a8a17f2a-8fb6-4f2d-8143-b55912a47aaf"
CSV = "efb0c6a2-fbf6-4067-9eea-d4f08f4a96d1"
DataFrames = ""
Gadfly = ""
HTTP = ""
HypothesisTests = ""
MLJ = ""
MLJBase = "aa8102d7-234b-4d37-98e6-e1286a0f2477"
MLJLinearModels = ""
MLJModels = ""
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = ""
PyPlots = ""
RDatasets = ""
Statistics = ""
StatsBase = ""
StatsFuns = ""

[compat]
julia = "1.5.0"
